using System.Diagnostics;

namespace ConsoleApp2
{
    internal class Program
    {
        static void Main(string[] args)
        {
            
            List<Product> products = new List<Product>
            {
                new Product("Хлеб белый нарезной", 55),
                new Product("Молоко 3.2%, 1 л", 85),
                new Product("Яйца куриные, 10 шт", 120),
                new Product("Сахар-песок, 1 кг", 60),
                new Product("Макароны спагетти, 450 г", 75),
                new Product("Рис белый, 1 кг", 110),
                new Product("Кофе молотый, 250 г", 350),
                new Product("Чай черный, 25 пакетиков", 200),
                new Product("Шоколад молочный", 90),
                new Product("Печенье овсяное", 110),
                new Product("Вода минеральная, 1.5 л", 50),
                new Product("Сок яблочный, 1 л", 130),
                new Product("Стиральный порошок, 3 кг", 400),
                new Product("Мыло жидкое для рук", 150),
                new Product("Гель для душа", 180),
                new Product("Шампунь", 220),
                new Product("Зубная паста", 190),
                new Product("Средство для мытья посуды", 120),
                new Product("Салфетки бумажные, 2 шт", 90),
                new Product("Одноразовые стаканчики, 50 шт", 130),
                new Product("Батарейки АА, 2 шт", 120),
                new Product("Фонарик карманный", 450),
                new Product("Ручка шариковая синяя", 25),
                new Product("Тетрадь 48 листов", 90),
                new Product("Карандаш чернографитный", 20),
                new Product("Ластик", 15),
                new Product("Точилка для карандашей", 35),
                new Product("Клей-карандаш", 50),
                new Product("Степлер", 250),
                new Product("Ножницы", 180),
                new Product("Блокнот А5", 150),
                new Product("Консервный нож", 350),
                new Product("Скотч широкий", 90),
                new Product("Мусорные пакеты, 30 л, 10 шт", 110),
                new Product("Губки для мытья посуды, 5 шт", 70),
                new Product("Фольга пищевая", 85),
                new Product("Свеча хозяйственная", 60),
                new Product("Керамическая кружка", 350),
                new Product("Стеклянная бутылка для воды", 450),
                new Product("Пластиковый контейнер для еды", 220),
                new Product("Разделочная доска", 300),
                new Product("Воздушный шарик", 40),
                new Product("Цветочный горшок", 200),
                new Product("Зеркало карманное", 180),
                new Product("Открытка", 85),
                new Product("Фотоальбом", 600),
                new Product("Корм для кошек, 400 г", 220),
                new Product("Наполнитель для кошачьего туалета", 300),
                new Product("Поводок для собаки", 450),
                new Product("Игрушка мячик", 150),
                new Product("Соль йодированная", 30),
                new Product("Перец черный молотый", 85),
                new Product("Мука пшеничная, 1 кг", 65),
                new Product("Томатная паста", 70),
                new Product("Огурцы свежие", 180),
                new Product("Помидоры свежие", 220),
                new Product("Яблоки", 150),
                new Product("Бананы", 90),
                new Product("Апельсины", 170),
                new Product("Картофель, 1 кг", 45),
                new Product("Лук репчатый, 1 кг", 40),
                new Product("Чеснок", 150),
                new Product("Морковь", 50),
                new Product("Свекла", 60),
                new Product("Капуста белокочанная", 55),
                new Product("Курица охлажденная, 1 кг", 350),
                new Product("Фарш говяжий, 500 г", 400),
                new Product("Сосиски молочные", 250),
                new Product("Колбаса докторская", 480),
                new Product("Сыр российский, 1 кг", 650),
                new Product("Творог 5%, 500 г", 120),
                new Product("Сметана 15%, 500 г", 110),
                new Product("Йогурт натуральный", 60),
                new Product("Кефир 2.5%, 1 л", 85),
                new Product("Маргарин", 50),
                new Product("Майонез", 110),
                new Product("Кетчуп", 95),
                new Product("Горчица", 70),
                new Product("Хлопья кукурузные", 130),
                new Product("Мюсли", 180),
                new Product("Орехи грецкие", 500),
                new Product("Изюм", 300),
                new Product("Чипсы картофельные", 110),
                new Product("Сухарики", 60),
                new Product("Вафли", 90),
                new Product("Зефир", 250),
                new Product("Мармелад", 180),
                new Product("Халва", 220),
                new Product("Сгущенное молоко", 120),
                new Product("Консервы кукуруза", 85),
                new Product("Консервы горошек", 85),
                new Product("Консервы фасоль", 90),
                new Product("Консервы шпроты", 200),
                new Product("Консервы сайра", 150),
                new Product("Икра кабачковая", 180),
                new Product("Сельдь соленая", 220),
                new Product("Масло оливковое", 450),
                new Product("Уксус столовый", 60),
                new Product("Сoda пищевая", 25),
                new Product("Дрожжи сухие", 40),
                new Product("Желатин", 80),
                new Product("Приправа для мяса", 55),
                new Product("Приправа для курицы", 55),
                new Product("Лавровый лист", 35),
                new Product("Корица", 90),
                new Product("Ванилин", 110),
                new Product("Крем для рук", 160),
                new Product("Бальзам для губ", 90),
                new Product("Тушь для ресниц", 340),
                new Product("Тональный крем", 520),
                new Product("Помада", 450),
                new Product("Лак для ногтей", 180),
                new Product("Дезодорант шариковый", 220),
                new Product("Дезодорант спрей", 250),
                new Product("Расческа", 150),
                new Product("Зубная щетка", 110),
                new Product("Бритвенный станок", 190),
                new Product("Средство для бритья", 270),
                new Product("Ватные диски", 60),
                new Product("Ватные палочки", 55),
                new Product("Туалетная бумага, 4 шт", 140),
                new Product("Бумажные полотенца", 180),
                new Product("Жидкость для снятия лака", 120),
                new Product("Крем для обуви", 210),
                new Product("Щетка для обуви", 130),
                new Product("Средство для чистки стекол", 190),
                new Product("Губка для посуды", 25),
                new Product("Мешки для мусора", 90),
                new Product("Пакеты фасовочные", 40),
                new Product("Диспенсер для мыла", 450),
                new Product("Ершик для унитаза", 180),
                new Product("Ароматические палочки", 300),
                new Product("Свеча декоративная", 220),
                new Product("Клей момент", 180),
                new Product("Клей ПВА", 90),
                new Product("Канцелярские кнопки", 30),
                new Product("Скрепки", 25),
                new Product("Линейка", 40),
                new Product("Корректор", 70),
                new Product("Папка-скоросшиватель", 110),
                new Product("Файлы для документов", 80),
                new Product("Конверт", 50),
                new Product("Альбом для рисования", 190),
                new Product("Акварельные краски", 350),
                new Product("Кисточка для красок", 120),
                new Product("Пластилин", 180),
                new Product("Цветная бумага", 110),
                new Product("Цветной картон", 130),
                new Product("Наклейки детские", 90),
                new Product("Мыльные пузыри", 85),
                new Product("Воздушный змей", 450),
                new Product("Надувной круг", 350),
                new Product("Детский рюкзак", 750),
                new Product("Ланчбокс", 450),
                new Product("Термос", 850),
                new Product("Набор столовых приборов", 600),
                new Product("Скатерть", 550),
                new Product("Деревянная ложка", 120),
                new Product("Венчик", 150),
                new Product("Терка", 250),
                new Product("Шумовка", 180),
                new Product("Лопатка кухонная", 200),
                new Product("Нож поварской", 800),
                new Product("Точилка для ножей", 450),
                new Product("Разделочная доска пластиковая", 200),
                new Product("Дуршлаг", 350),
                new Product("Сито", 280),
                new Product("Форма для выпечки", 400),
                new Product("Противень", 450),
                new Product("Фольга для запекания", 110),
                new Product("Пергамент", 90),
                new Product("Набор мисок", 600),
                new Product("Сотейник", 900),
                new Product("Сковорода гриль", 1200),
                new Product("Чайник заварочный", 400),
                new Product("Чайник электрический", 1500),
                new Product("Кофемолка", 2200),
                new Product("Блендер погружной", 2500),
                new Product("Миксер", 2800),
                new Product("Тостер", 1700),
                new Product("Электрочайник", 1300),
                new Product("Гриль электрический", 4500),
                new Product("Утюг", 3000),
                new Product("Фен", 1800),
                new Product("Пылесос", 7000),
                new Product("Вентилятор", 2500),
                new Product("Обогреватель", 4000),
                new Product("Лампа настольная", 1200),
                new Product("Лампочка LED", 150),
                new Product("Сетевой фильтр", 600),
                new Product("Батарейка крона", 180),
                new Product("Аккумуляторы AA", 450),
                new Product("Зарядное устройство", 850),
                new Product("Наушники", 1200),
                new Product("Флеш-накопитель 32GB", 800),
                new Product("Мышь компьютерная", 750),
                new Product("Коврик для мыши", 250),
                new Product("Клавиатура", 1500),
                new Product("Колонки портативные", 2200),
                new Product("Роутер", 2500),
                new Product("Вешалка плечики", 90),
                new Product("Прищепки для белья", 70),
                new Product("Сушилка для белья", 1200),
                new Product("Корзина для белья", 850),
                new Product("Ведро пластмассовое", 350),
                new Product("Тазик", 450),
                new Product("Швабра", 600),
                new Product("Веник", 250),
                new Product("Совок", 120),
                new Product("Грабли", 550),
                new Product("Лейка", 350),
                new Product("Секатор", 450),
                new Product("Перчатки садовые", 180),
                new Product("Пакеты для рассады", 60),
                new Product("Удобрение универсальное", 220),
                new Product("Земля цветочная", 150),
                new Product("Горшок торфяной", 30),
                new Product("Лопата садовая", 850),
                new Product("Грабли садовые", 650),
                new Product("Топор", 1200),
                new Product("Пила ножовка", 950),
                new Product("Молоток", 550),
                new Product("Отвертка крестовая", 350),
                new Product("Отвертка плоская", 350),
                new Product("Набор гаечных ключей", 1500),
                new Product("Пассатижи", 650),
                new Product("Рулетка", 250),
                new Product("Уровень", 600),
                new Product("Леска для триммера", 250),
                new Product("Масло моторное", 1800),
                new Product("Антифриз", 700),
                new Product("Омыватель стекла", 150),
                new Product("Щетка стеклоочистителя", 350),
                new Product("Коврик в салон", 1200),
                new Product("Ароматизатор в авто", 250),
                new Product("Держатель для телефона", 450),
                new Product("Компрессор автомобильный", 2200),
                new Product("Провода для прикуривания", 1200),
                new Product("Огнетушитель", 1500),
                new Product("Аптечка автомобильная", 600),
                new Product("Насос велосипедный", 450),
                new Product("Замок велосипедный", 850),
                new Product("Фара велосипедная", 350),
                new Product("Шлем велосипедный", 1800),
                new Product("Набор инструментов", 3500),
                new Product("Сумка хозяйственная", 550),
                new Product("Рюкзак городской", 1800),
                new Product("Зонт", 950),
                new Product("Дождевик", 350),
                new Product("Перчатки зимние", 650),
                new Product("Шарф", 550),
                new Product("Шапка", 750),
                new Product("Носки", 150),
                new Product("Крем для обуви", 180),
                new Product("Щетка для одежды", 250),
                new Product("Сумка-холодильник", 2200),
                new Product("Мангал", 1500),
                new Product("Шампуры", 350),
                new Product("Уголь для гриля", 250),
                new Product("Средство от комаров", 180),
                new Product("Солнцезащитный крем", 350),
                new Product("Пляжное полотенце", 650),
                new Product("Купальник", 1200),
                new Product("Плавки", 950),
                new Product("Очки плавательные", 450),
                new Product("Шапочка для плавания", 250),
                new Product("Нарукавники", 350),
                new Product("Круг надувной", 450),
                new Product("Матрас надувни", 2200),
                new Product("Насос для матраса", 850),
                new Product("Палатка двухместная", 4500),
                new Product("Спальник", 2800),
                new Product("Рюкзак туристический", 5500),
                new Product("Фонарь налобный", 950),
                new Product("Термос 1 л", 1200),
                new Product("Складной стул", 850),
                new Product("Стол походный", 1500),
                new Product("Компас", 450),
                new Product("Бинокль", 3500),
                new Product("Мяч футбольный", 1800),
                new Product("Мяч волейбольный", 1700),
                new Product("Мяч баскетбольный", 1900),
                new Product("Насос для мячей", 450),
                new Product("Скакалка", 250),
                new Product("Гантели 5 кг", 1200),
                new Product("Эспандер", 550),
                new Product("Коврик для йоги", 850),
                new Product("Велотренажер", 15000),
                new Product("Беговая дорожка", 45000),
                new Product("Гиря 16 кг", 2200),
                new Product("Шахматы", 950),
                new Product("Шашки", 450),
                new Product("Дартс", 850),
                new Product("Карты игральные", 150),
                new Product("Домино", 250),
                new Product("Пазл 1000 элементов", 650),
                new Product("Конструктор детский", 1800),
                new Product("Кукла", 1200),
                new Product("Машинка радиоуправляемая", 3500),
                new Product("Мягкая игрушка", 950),
                new Product("Набор доктора", 850),
                new Product("Набор инструментов", 750),
                new Product("Краски пальчиковые", 450),
                new Product("Кинетический песок", 650),
                new Product("Детский стол", 2500),
                new Product("Стульчик детский", 1800),
                new Product("Горшок детский", 850),
                new Product("Подгузники", 950),
                new Product("Влажные салфетки", 180),
                new Product("Присыпка детская", 220),
                new Product("Крем под подгузник", 250),
                new Product("Бутылочка для кормления", 450),
                new Product("Пустышка", 180),
                new Product("Прорезыватель", 150),
                new Product("Детское питание", 120),
                new Product("Пеленка", 350),
                new Product("Распашонка", 450),
                new Product("Ползунки", 400),
                new Product("Носочки детские", 150),
                new Product("Шапочка детская", 250),
                new Product("Комбинезон", 1200),
                new Product("Коляска прогулочная", 8500),
                new Product("Автокресло", 6500),
                new Product("Слинг", 2200),
                new Product("Рюкзак-кенгуру", 2800),
                new Product("Весы кухонные", 1200),
                new Product("Таймер", 350),
                new Product("Дозатор для жидкого мыла", 450),
                new Product("Ёршик для бутылок", 250),
                new Product("Подставка для зубных щёток", 180),
                new Product("Держатель для туалетной бумаги", 350),
                new Product("Коврик ванный", 550),
                new Product("Занавеска для ванной", 850),
                new Product("Смеситель", 2200),
                new Product("Лейка для душа", 950),
                new Product("Полотенце банное", 650),
                new Product("Полотенце махровое", 450),
                new Product("Халат банный", 1800),
                new Product("Тапочки домашние", 550),
                new Product("Тапочки банные", 350),
                new Product("Коврик придверный", 850),
                new Product("Одеяло", 2500),
                new Product("Подушка", 1500),
                new Product("Постельное белье", 2800),
                new Product("Плед", 2200),
                new Product("Наматрасник", 1800),
                new Product("Пододеяльник", 950),
                new Product("Простынь", 650),
                new Product("Наволочка", 350),
                new Product("Чехол для одежды", 450),
                new Product("Органайзер для белья", 850),
                new Product("Вешалка для галстуков", 250),
                new Product("Кофр для хранения", 1200),
                new Product("Коробка картонная", 150),
                new Product("Скотч упаковочный", 90),
                new Product("Шпагат", 60),
                new Product("Ножницы садовые", 450),
                new Product("Лейка садовая", 350),
                new Product("Опрыскиватель", 550),
                new Product("Лопата снеговая", 850),
                new Product("Скрепер для льда", 450),
                new Product("Ледорубы", 250),
                new Product("Санки", 1800),
                new Product("Лыжи", 4500),
                new Product("Коньки", 3500),
                new Product("Сноуборд", 6500),
                new Product("Защитный шлем", 2200),
                new Product("Наколенники", 950),
                new Product("Налокотники", 850),
                new Product("Защита для запястий", 750),
                new Product("Роликовые коньки", 4500),
                new Product("Скейтборд", 3800),
                new Product("Самокат", 3500),
                new Product("Гироскутер", 12000),
                new Product("Моноколесо", 25000),
                new Product("Электросамокат", 18000),
                new Product("Набор для вышивания", 650),
                new Product("Набор для вязания", 850),
                new Product("Пряжа", 350),
                new Product("Иглы для вязания", 150),
                new Product("Спицы", 250),
                new Product("Набор для бисероплетения", 550),
                new Product("Бисер", 180),
                new Product("Нитки мулине", 90),
                new Product("Канва", 120),
                new Product("Пяльцы", 250),
                new Product("Набор для лепки", 450),
                new Product("Глина полимерная", 550),
                new Product("Инструменты для лепки", 350),
                new Product("Набор для мыловарения", 1200),
                new Product("Набор для свечей", 950),
                new Product("Набор для выжигания", 850),
                new Product("Лобзик", 2200),
                new Product("Выжигательный аппарат", 1800),
                new Product("Гравёр", 3500),
                new Product("Набор красок по стеклу", 650),
                new Product("Витражные краски", 850),
                new Product("Кисти для рисования", 450),
                new Product("Мольберт", 2500),
                new Product("Холст", 550),
                new Product("Масляные краски", 1200),
                new Product("Акриловые краски", 950),
                new Product("Гуашь", 450),
                new Product("Пастель", 650),
                new Product("Уголь для рисования", 250),
                new Product("Бумага для акварели", 350),
                new Product("Лак для волос", 220),
                new Product("Гель для волос", 180),
                new Product("Воск для укладки", 250),
                new Product("Пена для бритья", 190),
                new Product("Лосьон после бритья", 270),
                new Product("Крем для лица", 450),
                new Product("Маска для лица", 350),
                new Product("Скраб для тела", 280),
                new Product("Пена для ванны", 220),
                new Product("Соль для ванны", 250),
                new Product("Масло для тела", 350),
                new Product("Дезодорант для ног", 180),
                new Product("Средство для снятия макияжа", 290),
                new Product("Вата хирургическая", 120),
                new Product("Бинт", 90),
                new Product("Пластырь", 60),
                new Product("Йод", 85),
                new Product("Зеленка", 75),
                new Product("Перекись водорода", 80),
                new Product("Активированный уголь", 55),
                new Product("Обезболивающее", 180),
                new Product("Жаропонижающее", 220),
                new Product("Противоаллергическое", 350),
                new Product("Назальный спрей", 280),
                new Product("Капли глазные", 320),
                new Product("Термометр электронный", 450),
                new Product("Тонометр", 2500),
                new Product("Глюкометр", 2200),
                new Product("Ингалятор", 1800),
                new Product("Грелка", 550),
                new Product("Пузырь для льда", 350)
            };
            Stopwatch stopwatch = new Stopwatch();
            Console.WriteLine("Введите название товара: ");
            string serchName = Console.ReadLine();
            stopwatch.Start();
            var prod = ProductSearch.BinSertch(products, serchName);
            stopwatch.Stop();
            Console.WriteLine(prod.name + " : " + prod.price + " : Время выполения бинарного поиска: " + stopwatch.ElapsedMilliseconds + "мс" );
            stopwatch.Restart();
            prod = ProductSearch.LinearSearchLinq(products, serchName);
            Console.WriteLine(prod.name + " : " + prod.price + " : Время выполения линейного поиска: " + stopwatch.ElapsedMilliseconds + "мс");
        }
        
        


    }
}
